# Generated by Django 6.0.7 on 2026-07-23 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="declined_by",
            field=models.ManyToManyField(
                blank=True, related_name="declined_orders", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
